name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential pkg-config libcunit1-dev liburing-dev libcunit1 libcunit1-doc libcunit1-dev
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTS=ON
      - name: Build
        run: cmake --build build -j
      - name: Run tests
        run: cd build && ctest -V

